method = 'SimVP'
spatio_kernel_enc = 3
spatio_kernel_dec = 3
model_type = 'unet'  # SimVP.V1
hid_S = 64
hid_T = 9
N_T = 2
N_S = 4
lr = 1e-3
batch_size = 16
root_dir = "7daysv2"
data_root = "7daysv2"
workers = 4
epochs = 200
