method = 'SimVP'
spatio_kernel_enc = 3
spatio_kernel_dec = 3
model_type = 'unet'  # SimVP.V1
hid_S = 64
hid_T = 3
N_T = 1
N_S = 4
lr = 1e-3
batch_size = 16
root_dir = "7days"
data_root = "7days"
workers = 4
epochs = 200
