method = 'UNet'
in_channels = 10
out_channels = 10
depth = 5
wf = 6
padding = True
batch_norm = True
pos_emb = False
up_mode = 'upconv'
lr = 1e-3
batch_size = 16
drop_path = 0
workers=0
sched = 'onecycle'